name: Build and Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set UTF-8 Code Page
        run: chcp 65001

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1
        with:
          nuget-version: '5.0.2'

      - name: Restore Solution
        run: nuget restore ${{ github.workspace }}/path/to/solution.sln
        env:
          NUGET_FEED: ${{ secrets.NUGET_FEED }}

      - name: Build Solution
        run: |
          msbuild ${{ github.workspace }}/path/to/solution.sln /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=false /p:SkipInvalidConfigurations=true /p:PackageLocation="${{ github.workspace }}/output" /p:Configuration=Release
        env:
          buildPlatform: 'Any CPU'
          buildConfiguration: 'Release'

      - name: Archive Build Artifacts
        run: |
          $sourceDirectory = "${{ github.workspace }}/output/Archive/Content/"
          $packageTmpDirectory = Get-ChildItem -Path $sourceDirectory -Recurse -Filter 'PackageTmp' -Directory | Select-Object -First 1

          if ($null -ne $packageTmpDirectory) {
              Write-Host "Found PackageTmp directory: $($packageTmpDirectory.FullName)"
              $archiveFile = "${{ github.workspace }}/output/${{ github.event.repository.name }}.zip"

              # Create the ZIP archive with the contents of PackageTmp
              Compress-Archive -Path "$($packageTmpDirectory.FullName)/*/" -DestinationPath $archiveFile -Force
          } else {
              Write-Host "PackageTmp directory not found."
              exit 1
          }
        shell: pwsh

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}
          path: ${{ github.workspace }}/output/${{ github.event.repository.name }}.zip


