name: Build and Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Set UTF-8 Code Page
      run: chcp 65001

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
      with:
        nuget-version: 5.0.2

    - name: Restore NuGet packages
      run: nuget restore ${{ env.SOLUTION }}
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Build Solution
      run: |
        msbuild ${{ env.SOLUTION }} /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=false /p:SkipInvalidConfigurations=true /p:PackageLocation="${{ github.workspace }}"
      env:
        SOLUTION: 'WebApp.sln'
        buildPlatform: 'Any CPU'
        buildConfiguration: 'Release'

    - name: Build ArchiveFile
      shell: pwsh
      run: |
        $sourceDirectory = Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath 'Archive/Content/'
        $packageTmpDirectory = Get-ChildItem -Path $sourceDirectory -Recurse -Filter 'PackageTmp' -Directory | Select-Object -First 1

        if ($packageTmpDirectory -ne $null) {
            Write-Output "Found PackageTmp directory: $($packageTmpDirectory.FullName)"
            Write-Output "::set-output name=PackageTmpDirectory::$($packageTmpDirectory.FullName)"

            $archiveFile = Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath '${{ env.APPLICATION_NAME }}.zip'

            # Create the ZIP archive with the contents of PackageTmp
            Compress-Archive -Path "$($packageTmpDirectory.FullName)/*/" -DestinationPath $archiveFile -Force
        } else {
            Write-Output "PackageTmp directory not found."
            throw "PackageTmp directory not found."
        }
      env:
        APPLICATION_NAME: 'YourAppName'

    - name: Publish Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.APPLICATION_NAME }}
        path: ${{ github.workspace }}
      env:
        APPLICATION_NAME: 'YourAppName'
